---

- name: Install Ubuntu Desktop
  apt:
    name: lxde
    state: latest
    update_cache: yes

- name: Install Remote Desktop Server
  apt:
    name: xrdp
    state: latest
    update_cache: yes

- name: Install VNC Server (whatever that is for)
  apt:
    name: vnc4server
    state: latest
    update_cache: yes

- name: Change Ubuntu User Password
  user:
    name: ubuntu
    update_password: always
    password: $1$SomeSalt$MTrfjA4WXc7dNfN6/aitu0