---

- name: Install Pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes

- name: Installing youtube-dl using Ansible pip module
  pip:
    name: youtube-dl 

- name: Download Dropbox 
  get_url: url=https://www.dropbox.com/download?plat=lnx.x86_64 
           dest=/home/ubuntu

- name: Download Script to Manage Dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/dropbox.py 
           dest=/usr/local/bin/dropbox

- name: Make Dropbox Script Executable 
  file: 
    path: /usr/local/bin/dropbox
    mode: +x

- name: Extract dropbox-lnx.x86_64-64.4.141.tar.gz into /home/ubuntu
  unarchive:
    src: /home/ubuntu/dropbox-lnx.x86_64-64.4.141.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: Create Directory
  file:
    path: /home/ubuntu/Dropbox/Videos/Yotevi
    state: directory
    owner: ubuntu

- name: Install Git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Get files via Git
  git:
    repo: 'https://github.com/fcmendoza/tubesc.git'
    dest: /home/ubuntu/tunesc
    version: master

- name: Copy Main Executable Script to Home Directory.
  copy:
    src: /home/ubuntu/tunesc/youtubesc.sh
    dest: /home/ubuntu/youtubesc.sh
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: u+x

- name: Copy Cookies File to Home Directory.
  copy:
    src: /home/ubuntu/tunesc/cookies.txt
    dest: /home/ubuntu/cookies.txt
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Copy dot Files to Home Directory
  copy:
    src: /home/ubuntu/tunesc/.bash_aliases
    dest: /home/ubuntu/.bash_aliases
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy varchive to Home Directory
  copy:
    src: /home/ubuntu/tunesc/varchive.txt
    dest: /home/ubuntu/varchive.txt
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy Main Service to Systemd Directory.
  copy:
    src: /home/ubuntu/tunesc/youtubedl.service
    dest: /lib/systemd/system/youtubedl.service
    remote_src: yes
    owner: root
    group: root

- name: Restart Main Service
  systemd:
    state: restarted
    daemon_reload: yes
    name: youtubedl

- name: Enable Main Service
  systemd:
    name: youtubedl
    enabled: yes

- name: Copy Dropbox Service to Systemd Directory
  copy:
    src: /home/ubuntu/tunesc/dropbox.service
    dest: /lib/systemd/system/dropbox.service
    remote_src: yes

- name: Start/Restart Dropbox Service
  systemd:
    state: restarted
    daemon_reload: yes
    name: dropbox

- name: Enable Dropbox Service
  systemd:
    name: dropbox
    enabled: yes

- name: Get Dropbox Status
  shell: "dropbox status"
  become: yes
  become_user: ubuntu
  register: hello

- debug: msg="{{ hello.stdout }}"

# After Dropbox has been installed as a systemd service we can now perform the following simplified steps:

# cd ~/Dropbox
# dropbox status

# Open url provided by 'dropbox status' to link computer to Dropbox.
# Then exclude folders from syncing by running 'dropbox exlude add' inside ~/Drobox folder.

# dropbox exclude add baretail/ baretailpro/ bc3/ bc4/ BeyondCompare/ BookNotes/ Books/ Camera\ Uploads/ colorpic/ DropboxApi/ Esad/ Express/ iOSdev/ Isos/ js_tests/ MarkPad/ minime/ Notes/ oem/ OneNote\ Notebooks/ Pictures/ Public/ titulo\ uanl/ TrackinForm/ Music/ Windirstat/ WindowTabs/ _Root/ 