---

- name: Install Pip
  apt:
    name: python-pip
    state: latest
    update_cache: yes

- name: Installing youtube-dl using Ansible pip module
  pip:
    name: youtube-dl 

- name: Download Dropbox 
  get_url: url=https://www.dropbox.com/download?plat=lnx.x86_64 
           dest=/home/ubuntu

- name: Download script to manage Dropbox
  get_url: url=https://www.dropbox.com/download?dl=packages/dropbox.py 
           dest=/home/ubuntu/dropbox.py 

- name: Extract dropbox-lnx.x86_64-64.4.141.tar.gz into /home/ubuntu
  unarchive:
    src: /home/ubuntu/dropbox-lnx.x86_64-64.4.141.tar.gz
    dest: /home/ubuntu
    remote_src: yes

- name: Create Directory
  file:
    path: /home/ubuntu/Dropbox/Videos/Yotevi
    state: directory
    owner: ubuntu

- name: Install Git
  apt:
    name: git
    state: latest
    update_cache: yes

- name: Get files via Git
  git:
    repo: 'https://github.com/fcmendoza/tubesc.git'
    dest: /home/ubuntu/tunesc
    version: master

- name: Copy Main Executable Script to Home Directory.
  copy:
    src: /home/ubuntu/tunesc/youtubesc.sh
    dest: /home/ubuntu/youtubesc.sh
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: u+x

- name: Copy Needed Files to Home Directory.
  copy:
    src: /home/ubuntu/tunesc/cookies.txt
    dest: /home/ubuntu/cookies.txt
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Copy dot files Home Directory
  copy:
    src: /home/ubuntu/tunesc/.bash_aliases
    dest: /home/ubuntu/.bash_aliases
    remote_src: yes
    owner: ubuntu
    group: ubuntu

- name: Copy Main Service to Systemd Directory.
  copy:
    src: /home/ubuntu/tunesc/youtubedl.service
    dest: /lib/systemd/system/youtubedl.service
    remote_src: yes
    owner: root
    group: root

- name: Restart Main Service
  systemd:
    state: restarted
    daemon_reload: yes
    name: youtubedl

- name: Enable Main Service
  systemd:
    name: youtubedl
    enabled: yes

#- name: Run Dropbox as user ubuntu
#  command: "python ~/dropbox.py start"
#    become: yes
#    become_user: ubuntu

